<a-entity id="quizZone" position="0 0 0">

  <a-entity class="answer" id="answer1" position="-1 1 -3">
    <a-text
      align="center"
      value="Answer 1"
      color="#FFF"
      position="0 0 0.1"
    ></a-text>
    <a-box
      position="0 0 0"
      depth="0.1"
      height="0.5"
      width="1"
      color="#4CC3D9"
    ></a-box>
  </a-entity>
  <a-entity class="answer" id="answer2" position="1 1 -3">
    <a-text
      align="center"
      value="Answer 2"
      color="#FFF"
      position="0 0 0.1"
    ></a-text>

    <a-box
      position="0 0 0"
      depth="0.1"
      height="0.5"
      width="1"
      color="#4CC3D9"
    ></a-box>
  </a-entity>
  <a-entity class="answer" id="answer3" position="-1 0 -3">
    <a-text
      align="center"
      value="Answer 3"
      color="#FFF"
      position="0 0 0.1"
    ></a-text>
    <a-box
      position="0 0 0"
      depth="0.1"
      height="0.5"
      width="1"
      color="#4CC3D9"
    ></a-box>
  </a-entity>

></a-entity>
